name: ActionsTest

on:
  pull_request:
        branches: 
          - main
        types: [opened, synchronize, reopened, labeled]
  label:
        types: [created, edited]    
jobs:
 init:
    runs-on: macos-latest
    
    steps: 
     - name: echo all lables
       run: |
        echo "Lables: ${{ github.event.pull_request.labels.*.name }}"

     - name: Extract and process labels
       id: extract-labels
       run: |
          for label in "${{ github.event.pull_request.labels.*.name }}"; do
            if [[ $label =~ v:(.*) ]]; then
              v_label="${BASH_REMATCH[1]}"
              echo "v: $v_label"
            elif [[ $label =~ brand:(.*) ]]; then
              brand_label="${BASH_REMATCH[1]}"
              echo "brand: $brand_label"   
            elif [[ $label =~ mode:(.*) ]]; then
              mode_label="${BASH_REMATCH[1]}"
              echo "mode: $mode_label"    
            elif [[ $label =~ os:(.*) ]]; then
              os_label="${BASH_REMATCH[1]}"
              echo "os: $os_label"          
            fi
          done


          echo "::set-output name=brand::${brand_label:-anywhere.app}"
          echo "::set-output name=version::${v_label:-1.0.0}"
          echo "::set-output name=mode::${mode_label:-dev-ts}"
          echo "::set-output name=os::${os_label:-macos-latest}"


     - name: Print data
       run: | 
            echo "Brand: ${{ steps.extract-labels.outputs.brand }}"
            echo "Version: ${{ steps.extract-labels.outputs.version }}"
            echo "Mode: ${{ steps.extract-labels.outputs.mode }}"

     - name: Setup checkout@v2
       uses: actions/checkout@v2

     - name: Setup Node 16.x runtime
       uses: actions/setup-node@v1 
       with:
         node-version: 16.x
                           
     - name: Cache node_modules  
       uses: actions/cache@v2
       with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

     - name: Set up JavaScript
       id: setup-js
       run: 
         echo "::set-output name=getData::\$(node -e \"console.log(JSON.stringify(require('../../../store/data.js').getData()))\")"


     - name: Store data
       run: | 
        echo "Mode: ${{ steps.setup-js.outputs.getData }}"